# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1333888373);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1333888493);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1334108927);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20120216115113");
user_pref("browser.startup.homepage_override.mstone", "rv:10.0.2");
user_pref("browser.syncPromoViewsLeft", 1);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 11);
user_pref("extensions.enabledAddons", "globalmenu@ubuntu.com:2.0.2,ubufox@ubuntu.com:1.0.2,langpack-en-ZA@firefox.mozilla.org:10.0.2,langpack-en-GB@firefox.mozilla.org:10.0.2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:10.0.2");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-10.0.2/extensions/globalmenu@ubuntu.com\",\"mtime\":1330889575000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-10.0.2/extensions/ubufox@ubuntu.com\",\"mtime\":1330889718000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-10.0.2/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1329402331000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-10.0.2/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1330889577000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-10.0.2/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1329402331000}}}]");
user_pref("extensions.lastAppVersion", "10.0.2");
user_pref("extensions.lastPlatformVersion", "10.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 103668);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_viewing_mixed", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1336479730);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
